### PR TITLE
Upgrade to `wmlandscape` 1.371.0 (Dec 2023 OWM)

### PR DESCRIPTION
**Pull request by Preskton**
Upgrades the plugin to use the latest version of `wmlandscape` as used on OWM as of December 2023.

This picks up new features like:

- The pipeline v2 "block" style
- Accelerators/Deaccelerators
- Links with text/constraints
- New Material style
- Newer react/other libraries

image

## TODO

- [x] Working `yarn install`
- [x] Working `yarn compile`
- [x] Local plugin loads & works as expected -- PRE-pipeline work
- [x] The following file needs updating to include recent pipeline work from OWM. https://github.com/damonsk/onlinewardleymaps/blob/master/frontend/wmlandscape/src/index.js
- [x] Update the language file: https://github.com/damonsk/vscode-wardley-maps/blob/master/syntaxes/wardleymap.tmLanguage.json
- [x] Include new snippets: https://github.com/damonsk/vscode-wardley-maps/blob/master/snippets/snippets.code-snippets
- [x] plugin loads and works as expected -- the [sample wardley map from OWM](https://onlinewardleymaps.com/#dl55NkOEsWLhOC6QMz) should render similarly

/cc https://github.com/damonsk/vscode-wardley-maps/issues/21

### CODE REVIEW

**Comment by Preskton** [comment]
## Working `yarn install`

Out of the box, running `yarn install` on the repo did not work. I had to adjust some dependencies such that it would. I am not a node person, so some of the changes might not have been strictly necessary.

- Compared [`package.json`](./package.json) to the latest OWM [`package.json`](https://github.com/damonsk/onlinewardleymaps/blob/master/frontend/package.json) and sync'd in changes
- Bumped `node-sass` from a Very Old version to the latest (`9.0.0`) to get past a `node-gyp` error that was looking for python2

**Comment by Preskton** [comment]
@damonsk for this:

> The following file needs updating to include recent pipeline work from OWM. https://github.com/damonsk/onlinewardleymaps/blob/master/frontend/wmlandscape/src/index.js

Could you please give me an example of what needs to be done to sync that into the plugin? If there's a PR or set of commits that help identify what changed, that'd be helpful, too.

At this point, I have the plugin building and running successfully with bumped dependencies. Next, I'll work on that ^ to bring in the latest features, but I just need a bit of guidance to move forward. Thank you!

**Comment by damonsk** [comment]
> Could you please give me an example of what needs to be done to sync that into the plugin?

I can see the pipelinev2 is already included - https://github.com/damonsk/onlinewardleymaps/blob/1e2ebc5ca653525953880e395fbc00cb354000a6/frontend/wmlandscape/src/index.js#L196

It's usually any new js files and any dependencies but a quick look suggests they're already included.  I "think" this might be enough.  A couple of tests running the extension and using the new syntaxt (https://github.com/damonsk/onlinewardleymaps/blob/1e2ebc5ca653525953880e395fbc00cb354000a6/frontend/src/__tests__/GoldenMasterMapText.txt#L67) will confirm.

**Comment by damonsk** [comment]
> [ ] Update the language file: https://github.com/damonsk/vscode-wardley-maps/blob/master/syntaxes/wardleymap.tmLanguage.json

You can reference this commit (https://github.com/damonsk/onlinewardleymaps/commit/955bc84b3b4bbbdc487fccce011a6f5cf19cd4ac) which is the equivalent from OWM.

**Comment by damonsk** [comment]
Just noticed that you'll also pull in the accelerate/deaccelerate components.   Whilst devdone i've not publicly shared it.  

```
accelerator foo [0.63, 0.44]
deaccelerator bar [0.67, 0.53]
```

Details: damonsk/onlinewardleymaps/#56 

The same runbook would apply to this.

Up to you if you wish to add.

**Comment by Preskton** [comment]
> > Could you please give me an example of what needs to be done to sync that into the plugin?
> 
> I can see the pipelinev2 is already included - https://github.com/damonsk/onlinewardleymaps/blob/1e2ebc5ca653525953880e395fbc00cb354000a6/frontend/wmlandscape/src/index.js#L196
> 
> It's usually any new js files and any dependencies but a quick look suggests they're already included. I "think" this might be enough. A couple of tests running the extension and using the new syntaxt (https://github.com/damonsk/onlinewardleymaps/blob/1e2ebc5ca653525953880e395fbc00cb354000a6/frontend/src/__tests__/GoldenMasterMapText.txt#L67) will confirm.

So I'm not a super duper NPM/Node person, but I can't seem to find a reference to `PipelineVersion2` in the [latest published version of `wmlandscape` in NPM](https://www.npmjs.com/package/wmlandscape?activeTab=readme) (`1.360.0`). It was published 15 days ago, which seems very new, which is why I'm confused that I'm not seeing any refs to the new pipeline stuff there.

Do you mind checking to see if everything was published in that version? Apologies if this is a silly question. :)

**Comment by damonsk** [comment]
Not a silly question, the publish was removed when I merged beta.  I've restored this and builds are being published again.

You should be able to pull in version wmlandscape@1.369.0

This also has accelerate/deaccelerate from damonsk/onlinewardleymaps#56

Let me know how you get on with this.

**Comment by damonsk** [comment]
As accelerators have been added, you'll likely need to modify App.js and pass through mapAccelerators to the `MapView` component.

Check this commit and hopefully the above makes sense. 

https://github.com/damonsk/onlinewardleymaps/commit/56b704a9cd35ee5dba09be651e658e5edd0572e1#diff-40cd278b9a67f8df2e21fdc09e83dfd25b6035f927282928487e1516fe348049

**Comment by Preskton** [comment]
> Not a silly question, the publish was removed when I merged beta. I've restored this and builds are being published again.
> 
> You should be able to pull in version ~wmlandscape@1.369.0~ wmlandscape@1.371.0
> 
> This also has accelerate/deaccelerate from [damonsk/onlinewardleymaps#56](https://github.com/damonsk/onlinewardleymaps/issues/56)
> 
> Let me know how you get on with this.

Great, that version has the goods. Now just battling vscode not rendering anything after the React upgrade -- but digging in. :)

**Comment by damonsk** [comment]
> As accelerators have been added, you'll likely need to modify App.js and pass through mapAccelerators to the `MapView` component.
> 
> 
> 
> Check this commit and hopefully the above makes sense. 
> 
> 
> 
> https://github.com/damonsk/onlinewardleymaps/commit/56b704a9cd35ee5dba09be651e658e5edd0572e1#diff-40cd278b9a67f8df2e21fdc09e83dfd25b6035f927282928487e1516fe348049

@Preskton check this if you're struggling getting it to render. 

Also when you debug the extension and open Display Map (from command palette) you can then open Dev Tools just like in chrome by using the command palette. This normally helps debug.

**Comment by Preskton** [comment]
> you can then open Dev Tools just like in chrome by using the command palette. This normally helps debug.

omg this is SO helpful. thank you, thank you.

**Comment by Preskton** [comment]
> > As accelerators have been added, you'll likely need to modify App.js and pass through mapAccelerators to the `MapView` component.
> > Check this commit and hopefully the above makes sense.
> > [damonsk/onlinewardleymaps@56b704a#diff-40cd278b9a67f8df2e21fdc09e83dfd25b6035f927282928487e1516fe348049](https://github.com/damonsk/onlinewardleymaps/commit/56b704a9cd35ee5dba09be651e658e5edd0572e1#diff-40cd278b9a67f8df2e21fdc09e83dfd25b6035f927282928487e1516fe348049)
> 
> @Preskton check this if you're struggling getting it to render.
> 
> Also when you debug the extension and open Display Map (from command palette) you can then open Dev Tools just like in chrome by using the command palette. This normally helps debug.

Woohoo, that was it - piping in the `accelerators` bit was what it wanted! Now to clean things up & issue a real PR! Thanks so much for your help!

image

**Comment by Preskton** [comment]
Alrighty, after:

- loading in the accelerators
- some final updates to the snippets for acc/deacc
- finalizing the grammar file

I think this looks pretty good.

One thing I noticed is that after opening a file, I have to click into the text editor to trigger the map to render. I'll assume this is something I introduced and try to fix it as part of this PR.

**Comment by damonsk** [comment]
All merged and published to vsmarketplace.  Should be live soon.  

Thanks @Preskton.  

https://marketplace.visualstudio.com/items?itemName=damonsk.vscode-wardley-maps

**Pull request merged**
